### ISSUE TITLE
大哥我和你学的不是一个javaweb吧

### ISSUE THREAD

**Issue by XiaoZhong233** [29DCH/LovingHome-Real-Estate-Platform#1]
5555，可以要大佬联系方式吗？以后多多交流。同样我也是做课设可是我的系统很简单  噗
我的邮箱是 610596547@qq.com

**Comment by 29DCH** [comment]
qq:2265940560




------------------ 原始邮件 ------------------
发件人: "MingHanYan"<notifications@github.com>;
发送时间: 2019年5月17日(星期五) 晚上10:45
收件人: "29DCH/LovingHome-Real-Estate-Platform"<LovingHome-Real-Estate-Platform@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [29DCH/LovingHome-Real-Estate-Platform] 大哥我和你学的不是一个javaweb吧 (#1)




5555，可以要大佬联系方式吗？以后多多交流
